//
// Milkyway Hierarchical Verilog Dump:
// Generated on 11/28/2025 at 20:09:05
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :control_pad.mw
// Cell Name    :spef
// Hierarchy delimiter:'/'
// Write Command : write_verilog -no_physical_only_cells -no_unconnected_cells -no_tap_cells ../output/control_pad_final.v
//


module control_pad (rd , zero , clk , rst_ , opcode , sel , data_e , 
    halt , inc_pc , ld_pc , ld_ac , ld_ir , wr );
output rd ;
input  zero ;
input  clk ;
input  rst_ ;
input  [2:0] opcode ;
output sel ;
output data_e ;
output halt ;
output inc_pc ;
output ld_pc ;
output ld_ac ;
output ld_ir ;
output wr ;


wire [2:0] i_control_state ;
wire [2:0] opcode_pad ;

NOR2X2 U25 (.Y ( data_e_pad ) , .A ( n15 ) , .B ( n14 ) ) ;
NOR3X4 U27 (.Y ( wr_pad ) , .A ( i_control_state[2] ) , .B ( opcode_pad[0] ) 
    , .C ( n16 ) ) ;
CLKINVX2 U3 (.Y ( n4 ) , .A ( n10 ) ) ;
NOR3BX2 U26 (.Y ( ld_ac_pad ) , .AN ( n15 ) , .B ( i_control_state[2] ) 
    , .C ( n14 ) ) ;
NOR3BX2 U23 (.Y ( halt_pad ) , .AN ( n12 ) , .B ( opcode_pad[0] ) , .C ( n11 ) ) ;
DFFRX1 i_control_state_reg_2_ (.RN ( rst_pad ) , .Q ( i_control_state[2] ) 
    , .QN ( n21 ) , .D ( n18 ) , .CK ( clk_pad ) ) ;
OAI211X2 U16 (.A1 ( n22 ) , .A0 ( i_control_state[2] ) , .C0 ( n6 ) 
    , .Y ( rd_pad ) , .B0 ( n7 ) ) ;
NAND2BX1 U18 (.Y ( n10 ) , .B ( opcode_pad[0] ) , .AN ( n16 ) ) ;
OAI211X2 U22 (.A1 ( n10 ) , .A0 ( i_control_state[2] ) , .C0 ( n11 ) 
    , .Y ( inc_pc_pad ) , .B0 ( n9 ) ) ;
PI i_rst (.PAD ( rst_ ) , .C ( rst_pad ) ) ;
PI i_clk (.PAD ( clk ) , .C ( clk_pad ) ) ;
PI i_zero (.PAD ( zero ) , .C ( zero_pad ) ) ;
PI i_opcode_0 (.PAD ( opcode[0] ) , .C ( opcode_pad[0] ) ) ;
PI i_opcode_1 (.PAD ( opcode[1] ) , .C ( opcode_pad[1] ) ) ;
PI i_opcode_2 (.PAD ( opcode[2] ) , .C ( opcode_pad[2] ) ) ;
PO8 i_rd (.PAD ( rd ) , .I ( rd_pad ) ) ;
PO8 i_wr (.PAD ( wr ) , .I ( wr_pad ) ) ;
PO8 i_ld_ir (.PAD ( ld_ir ) , .I ( ld_ir_pad ) ) ;
PO8 i_ld_ac (.PAD ( ld_ac ) , .I ( ld_ac_pad ) ) ;
PO8 i_ld_pc (.PAD ( ld_pc ) , .I ( n4 ) ) ;
PO8 i_inc_pc (.PAD ( inc_pc ) , .I ( inc_pc_pad ) ) ;
PO8 i_halt (.PAD ( halt ) , .I ( halt_pad ) ) ;
PO8 i_data_e (.PAD ( data_e ) , .I ( data_e_pad ) ) ;
PO8 i_sel (.PAD ( sel ) , .I ( n17 ) ) ;
OAI21XL U15 (.A1 ( n23 ) , .A0 ( n5 ) , .Y ( n6 ) , .B0 ( n15 ) ) ;
DFFRXL i_control_state_reg_1_ (.RN ( rst_pad ) , .Q ( i_control_state[1] ) 
    , .QN ( n22 ) , .D ( n17 ) , .CK ( clk_pad ) ) ;
AND2XL U12 (.Y ( n3 ) , .B ( opcode_pad[1] ) , .A ( opcode_pad[2] ) ) ;
NOR2XL U13 (.Y ( n12 ) , .A ( opcode_pad[2] ) , .B ( opcode_pad[1] ) ) ;
NOR2XL U14 (.Y ( n15 ) , .A ( n3 ) , .B ( n12 ) ) ;
NAND3XL U17 (.Y ( n16 ) , .A ( opcode_pad[2] ) , .B ( opcode_pad[1] ) 
    , .C ( n13 ) ) ;
NAND4XL U20 (.Y ( n9 ) , .B ( opcode_pad[0] ) , .C ( n12 ) , .A ( n13 ) 
    , .D ( zero_pad ) ) ;
DFFRXL i_control_state_reg_0_ (.RN ( rst_pad ) , .Q ( i_control_state[0] ) 
    , .QN ( n23 ) , .D ( n19 ) , .CK ( clk_pad ) ) ;
NOR2X2 U28 (.Y ( ld_ir_pad ) , .A ( n22 ) , .B ( i_control_state[0] ) ) ;
NOR2X2 U29 (.Y ( n17 ) , .A ( n20 ) , .B ( n13 ) ) ;
NOR2XL U30 (.Y ( n13 ) , .A ( i_control_state[1] ) , .B ( i_control_state[0] ) ) ;
NOR2XL U31 (.Y ( n20 ) , .A ( n23 ) , .B ( n21 ) ) ;
INVXL U32 (.Y ( n7 ) , .A ( ld_ir_pad ) ) ;
INVXL U33 (.Y ( n14 ) , .A ( n13 ) ) ;
NOR2XL U34 (.Y ( n5 ) , .A ( i_control_state[1] ) , .B ( n21 ) ) ;
NAND3XL U35 (.Y ( n11 ) , .A ( i_control_state[1] ) , .B ( i_control_state[0] ) 
    , .C ( i_control_state[2] ) ) ;
AOI2BB1XL U36 (.A1N ( i_control_state[2] ) , .Y ( n19 ) , .A0N ( n22 ) 
    , .B0 ( n5 ) ) ;
NAND2BXL U37 (.Y ( n18 ) , .B ( n7 ) , .AN ( n20 ) ) ;
endmodule


